### ISSUE TITLE
Offcanvas + android + dropdown = closed menu

### ISSUE THREAD

**Issue by theMikeD** [jasny/bootstrap#412] opened 2015-09-28 16:32 UTC
http://www.jasny.net/bootstrap/examples/navmenu-push/

1.Visit that site on an android device
2. open the menu 
3. click the dropdown to open it
4. click the dropdown to close it

Result: the menu closes. It should not.

**Comment by MikiSoft** [comment] 2016-05-16 22:12
I have the same issue on Firefox (using PC).

**Comment by jasny** [comment] 2016-06-08 19:24
Should be fixed with #405. Please try the master branch. Reopen the ticket if the issue isn't solved in master.

**Closed by jasny** 2016-06-08 19:24 UTC
