### ISSUE TITLE
Menu drop-down inside another drop-down

### ISSUE THREAD

**Issue by blundercode** [jasny/bootstrap#440] opened 2016-02-01 20:47 UTC
Is it possible have a drop-down within another drop-down? whenever I try and click on the second drop-down it closes the current drop-down.
**Like this-**
![image](https://cloud.githubusercontent.com/assets/11480423/12730157/b4d06410-c8e7-11e5-93e3-7e1906545ac1.png)

**MY code**

![image](https://cloud.githubusercontent.com/assets/11480423/12730634/0fb3c104-c8ea-11e5-92ed-e9d1ae872101.png)

**Comment by zetoun17fr** [comment] 2016-04-29 15:43
Hello
i had the same issue, you may solved this bug by adding this line in your css : 
`.dropdown-backdrop {left:210px} `
replace 210px with your menu width, 
this work only if your offcanvas menu is at the left of the screen

source :  http://getbootstrap.com/javascript/#dropdowns

> On mobile devices, opening a dropdown adds a .dropdown-backdrop as a tap area for closing dropdown menus when tapping outside the menu, a requirement for proper iOS support.

**Comment by jasny** [comment] 2016-06-08 19:16
Duplicate of #230. Not fixed, but has a workaround.

**Closed by jasny** 2016-06-08 19:16 UTC
Labels: duplicate
