### ISSUE TITLE
Link's in dropdowns not working in Offcanvas on Smartphones

### ISSUE THREAD

**Issue by benzon** [jasny/bootstrap#379] opened 2015-06-14 20:40 UTC
Links in dropdowns dont work on smartphones, work in browser tho but should work on Smartphones, dont make sence any other way.

**Comment by Mickroz** [comment] 2015-08-27 12:06
got the same problem.

**Comment by jasny** [comment] 2016-01-08 04:54
Duplicate of #374

**Closed by jasny** 2016-01-08 04:54 UTC
Labels: duplicate
