### ISSUE TITLE
swipe support

### ISSUE THREAD

**Issue by ColonelMillerSG21** [jasny/bootstrap#472] opened 2016-08-19 19:35 UTC
I was wondering about swipe support. This would be an amazing feature. One of the few features bootstrap is missing compared to Google Polymer or Syiro. I'm not sure how Syiro solves this but polymer seems to solve it in a way that isn't possible in bootstrap. Here is an example:
http://stroblindustries.com/devcenter/index.html?product=syiro&doc=theming

**Comment by Minstel** [comment] 2017-02-22 04:55
Duplicate of https://github.com/jasny/bootstrap/issues/154

**Closed by Minstel** 2017-02-22 04:55 UTC
