### ISSUE TITLE
Offcanvas Push Menu not scrolling when items expand

### ISSUE THREAD

**Issue by ReaVerHC** [jasny/bootstrap#348] opened 2015-03-06 12:52 UTC
Hey mate, thanks for an awesome plugin.

I am trying to implement the push menu in a project but noticed that when you expand the offcanvas menu items that you cannot scroll vertically if the menu gets longer than your view port. It's as if the menu is "locked" from scrolling vertically. I tried it on your example page and it does the same as in my project: https://jasny.github.io/bootstrap/examples/navmenu-push/ . I tested it on the iPhone 4s.

I tried to see if someone else had this issue but can't find anything so I'm not sure if you are aware of this.

Thanks again

**Comment by siwwar** [comment] 2015-03-10 09:55
I have got the same problem when I used the Chrome Developer Tools Device Mode (Emulator):

![image](https://cloud.githubusercontent.com/assets/1453816/6554527/c1c76d08-c66d-11e4-9c6a-bae46ad9c8ca.png)

**Comment by shpuntj** [comment] 2015-03-11 01:37
Experiencing the same issue as well, reverted back to v3.1.2 until issue has been resolved.

**Comment by ReaVerHC** [comment] 2015-03-14 10:50
@shpuntj Does v3.1.2 not have this issue?

**Comment by shpuntj** [comment] 2015-03-17 19:15
@ReaVerHC version 3.1.2 does not have the issue.

**Comment by cqcsobreyra** [comment] 2015-03-19 20:43
the problem is that overflow-y is set to auto for navmenu-fixed-left, but not for navmenu-fixed-right.

**Comment by ReaVerHC** [comment] 2015-03-19 22:33
@cqcsobreyra Thanks for the reply, is there a chance you can drop it in a fiddle or something please? I'm a bit intermediate with regards to editing jquery/javascript.

**Comment by s6admin** [comment] 2015-04-15 20:09
We have the same issue as well (demo page and custom implementation). Tested on Android 5.1, Safari iOS 7 iPhone. 

Even explicitly forcing overflow-y:scroll !important; doesn't help. This one is difficult to debug because it works on every test case we've tried on desktop.

**Comment by suslovjb** [comment] 2015-05-09 06:14
great plugin.. have the same issue in https://jasny.github.io/bootstrap/examples/navmenu-push/ .. cant scroll from chrome and firefox (android) in landscape..

**Comment by wkentdag** [comment] 2015-06-23 20:11
@ReaVerHC if you just specify v3.1.2 exactly (in your `bower.json`, for example) that should do the trick. Unfortunately, reverting to 3.1.2 does not solve the problem on mobile for me (tested on iphone 6). 

For 3.1.3, I was able to scroll the menu by wrapping the contents of the navmenu in a container, e.g. : 
```
<nav id="#sidebar" class="navmenu navmenu-fixed-left offcanvas" role="navigation">
  <div class="sidebar-container" style="height:100%;overflow-y:scroll;">
    <h1> Push menu will scroll with content overflow on y-axis</h1>
        ...
  </div>
</nav>
```

I tested the above solution on desktop (chrome, ff, safari) and it works, but unfortunately it's still broken for mobile, so i'm working around it by collapsing my sidebar content under header categories until it's fixed.

**Comment by nolaandy** [comment] 2015-06-24 21:08
I have since reverted back to v3.1.2 and it does indeed fix the problem of the mobile sidebar not scrolling.

Unfortunately it created another problem for me.

Now ever time I close the off-canvas sidebar and go back to the page, I can't scroll up or down on the page anymore.

If I go to a new page, I can scroll everywhere, but as soon as I open the off-canvas nav then close it my screen allows no scrolling from whatever part of the website I was last on.

Anyone heard of this issue?

**Comment by carefulmistake** [comment] 2015-07-09 14:56
Dropping to 3.1.2 fixed this for me as well.  http://cdnjs.com/libraries/jasny-bootstrap/3.1.2

**Comment by pikos-apikos** [comment] 2015-07-16 16:54
Dropping to 3.1.2 fixed this for me too

**Comment by observerslee** [comment] 2015-07-24 04:59
Dropping back to 3.1.2 fixes the scroll issue.

**Comment by Julesman** [comment] 2015-08-06 23:05
I'm using the offcanvas reveal functionality and just found that the demo here has the problem being discussed here, so it's not a matter of implementation. Unfortunately, this is a total deal killer and will force me to look for another solution if not fixed. Also the lack of a fixed body in 3.1.2 is also a deal killer. If it's possible to fix this, please do so. I can see that MANY people would really appreciate it and it would make this one of the very best solutions for creating a reveal mobile menu. Thanks a lot for you time and effort.

**Comment by LunkRat** [comment] 2015-08-07 15:12
I've been implementing the offcanvas navmenu for a client project this week, and I am in agreement with @Julesman that this brilliant and wonderful project is rendered useless by these bugs. I also noticed that the issues appear in the v3.1.3 demo. 

I did get the menu scroll working (I'm using `navmenu-fixed-right`) and I was able to fix the touch problem described in #230. Here's what I did:
1. Downgraded to version 3.1.2 JS and CSS files from https://github.com/jasny/bootstrap/releases/download/v3.1.2/jasny-bootstrap-3.1.2-dist.zip
2. Added the following CSS to get my right-side navmenu to scroll when it has open dropdowns:
```
.navmenu-fixed-left,
.navmenu-fixed-right,
.navbar-offcanvas {
  overflow-y: auto;
}
```
3. Added the following CSS to fix #230: 
```
.offcanvas .navmenu-nav.dropdown-menu {
  position:relative;
}
```

Two bugs remain: 
- The body scrolls when you scroll past the bottom of the navmenu. 
- The menu hides if you _close_ a dropdown menu

**Comment by Julesman** [comment] 2015-08-13 18:59
SOLVED!!!! Sort of... Maybe... :)
Use 3.1.2. Then apply position:fixed; to .canvas-slid or possibly .canvas.canvas-slid. 
Actually, I'm using 3.1.2 js and 3.1.3 css. Doubt the css version matters.

**Comment by Julesman** [comment] 2015-08-18 01:59
My solution works with 3.1.3. The following was required on one of my sites to make it work. Not sure why.

Anybody out there? IT WORKS!!!! :) .... I think.

ul.nav {float:left;}

**Comment by vangorra** [comment] 2016-01-04 16:32
Even with the suggestions in this issue, scrolling the menu on Chrome (Android) still doesn't work. I'm using 3.1.3.
Using the chrome remote inspector, I can see a scrollbar is added but scroll doesn't work. I went as far as to disable all the styles on the navmenu and add my own overflow-y, it still doesn't help. As this point, I don't think CSS is the issue. What other observations has other people seen?

**Comment by bustaramz** [comment] 2016-02-22 11:03
This worked for me, tested on iPhone 6:

In the 3.2.3 javascript file change:


`  OffCanvas.prototype.disableScrolling = function() {
    var bodyWidth = $('body').width()
    var prop = 'padding-' + this.opposite(this.placement)

    if ($('body').data('offcanvas-style') === undefined) {
      $('body').data('offcanvas-style', $('body').attr('style') || '')
    }
      
    $('body').css('overflow', 'hidden')

    if ($('body').width() > bodyWidth) {
      var padding = parseInt($('body').css(prop), 10) + $('body').width() - bodyWidth
      
      setTimeout(function() {
        $('body').css(prop, padding)
      }, 1)
    }
    //disable scrolling on mobiles (they ignore overflow:hidden)
    $('body').on('touchmove.bs', function(e) {
      e.preventDefault();
    });
  }`

to

 ` OffCanvas.prototype.disableScrolling = function() {
    var bodyWidth = $('body').width()
    var prop = 'padding-' + this.opposite(this.placement)

    if ($('body').data('offcanvas-style') === undefined) {
      $('body').data('offcanvas-style', $('body').attr('style') || '')
    }
      
    $('body').css('overflow', 'hidden')
    $('#myNavmenu').css('height', $(window).height())

    if ($('body').width() > bodyWidth) {
      var padding = parseInt($('body').css(prop), 10) + $('body').width() - bodyWidth
      
      setTimeout(function() {
        $('body').css(prop, padding)
      }, 1)
    }
    //disable scrolling on mobiles (they ignore overflow:hidden)
    $('body').on('touchmove.bs', function (e) {
        if (!$(e.target).is('#myNavmenu, #myNavmenu ul, #myNavmenu li, #myNavmenu li a')) {
            e.preventDefault();
        }
    });
  }`

Maybe there are some CSS changes needed too,
but this was the main reason why it wasn't working.

Good luck!

**Comment by Bennethon** [comment] 2016-04-19 22:09
I don't understand why this issue is closed. It is still a problem. I have 3.1.3, and I still have to implement the hack workarounds in this thread to make it scroll properly.

**Closed** 2016-04-20 05:44 UTC
