### ISSUE TITLE
Iphone issue

### ISSUE THREAD

**Issue by syedtabeeb** [jasny/bootstrap#431] opened 2016-01-04 07:57 UTC
the offcanvas push menu wont close when clicked on any part of the page in Iphone n Ipad....also there is a delay  in opening of the offcanvas menu in iphone..... it works fine with other android devices and on desktop

**Comment by jasny** [comment] 2016-01-04 22:18
@syedtabeeb If possible, please fix the issue and send a pull request.

**Comment by cutelee888** [comment] 2016-01-19 09:02
Hi, yeah! i'm looking for this issue to be fix. And another one issue is:
- when iphone user use safari browser to open the website, then opening the push menu, and hand scrolling the content to bottom, can saw the menu keep moving upwards.
This issue won't happens on web or android. only iphone user with safari browser.

**Comment by vitalijusch** [comment] 2016-01-29 14:19
@cutelee888 You could prevent the menu and content from scrolling, by adding `position: fixed ` to body element when navigation is opened.

**Comment by samfrjn11** [comment] 2016-04-12 08:38
Autohiding the menu on iOS needs a small change in the javascript file.

`if (this.options.autohide)
      $(document).on('click', $.proxy(this.autohide, this))`
to
```
if (this.options.autohide)
      $(document).on('click touchstart', $.proxy(this.autohide, this))
```

**Comment by jasny** [comment] 2016-06-08 19:22
Duplicate of #415. Solved with PR

**Closed by jasny** 2016-06-08 19:22 UTC
Labels: duplicate
