### ISSUE TITLE
Is the mixins.scss file missing?

### ISSUE THREAD

**Issue by eversoclever** [jasny/bootstrap#411] opened 2015-09-24 17:21 UTC
The jasny-bootstrap.scss file tries to import a missing mixins.scss file.

**Comment by drtzack** [comment] 2015-10-11 17:05
same here

**Comment by jasny** [comment] 2016-01-07 23:46
@eversoclever or @drtzack It would be great if you could make a pull request for this.

**Comment by jasny** [comment] 2016-01-08 20:31
Duplicate of #395

**Closed by jasny** 2016-01-08 20:31 UTC
Labels: duplicate
