### ISSUE TITLE
Scroll issue, page " keeps going

### ISSUE THREAD

**Issue by benzon** [jasny/bootstrap#380] opened 2015-06-14 20:41 UTC
When you scroll the menu and if you keep scrolling when you hit the bottom, content and offcanvas menu will get out of "shape" looks awfull!

**Comment by Minstel** [comment] 2017-01-19 09:39
@benzon I do not see this happening in 3.1.3 version.

**Comment by Minstel** [comment] 2017-02-25 11:01
Duplicate of https://github.com/jasny/bootstrap/issues/467

**Closed by Minstel** 2017-02-25 11:01 UTC
