### ISSUE TITLE
Incorrect display input field, if filename too long.

### ISSUE THREAD

**Issue by andreyshade** [jasny/bootstrap#407] opened 2015-09-10 14:24 UTC
![error_file_input_exapmle](https://cloud.githubusercontent.com/assets/10078161/9790719/38792582-57e0-11e5-97d7-8397a8bf966b.JPG)

**Comment by jasny** [comment] 2016-01-08 04:41
Duplicate of #263

**Closed by jasny** 2016-01-08 04:41 UTC
Labels: duplicate
