### ISSUE TITLE
off-canvas no easing on open

### ISSUE THREAD

**Issue by codertingtong** [jasny/bootstrap#512] opened 2017-02-10 10:04 UTC
hi,
not sure where I am missing this. the menu on open is not easing. please see markup here.
thank you for any help.
http://jsfiddle.net/p2pz5p06/

**Comment by wordpresspluginpro** [comment] 2017-02-17 21:11
Chrome seems to have a problem with the right menu.  If you take a look at mine, the right menu doesn't push the content when opened.  It pops into place.  

https://www.wordpressthemepro.com/

I got the menu animation to work using the following, but the content still doesn't animate:

.navmenu-fixed-right {
	left: auto !important;
}
.navmenu-fixed-left {
	right: auto !important;
}

**Comment by muhammad-ihsan** [comment] 2017-02-17 21:46
hi @wordpresspluginpro why my body code looks like this [http://image.prntscr.com/image/908d060684ae451c9229b56b1ccd4c1b.png](image)

**Comment by wordpresspluginpro** [comment] 2017-02-17 22:33
@muhammad-ihsan it's the javascript that applies the animation that adds the css to your body

**Comment by muhammad-ihsan** [comment] 2017-02-17 22:41
@wordpresspluginpro yes sir i mean why return top and left position. I use` navmenu-fixed-right`

**Comment by wordpresspluginpro** [comment] 2017-02-18 17:11
@muhammad-ihsan hmm not sure, good question.  Javascript is hard to troubleshoot, especially if you didn't write it.

**Comment by muhammad-ihsan** [comment] 2017-02-18 21:29
@wordpresspluginpro the javascript is not working well with my current project, i use these offcanvas in various project but this time is sucks. Here is the output:

![](http://image.prntscr.com/image/17379668c16d49acbd1e1d91a8d1c13b.png)

if you dont mind, please take a look on the [live version](http://v2.isbanban.org)
PS: correct me if there is something missed

**Comment by wordpresspluginpro** [comment] 2017-02-19 01:38
One of your other plugins might be causing a conflict.  Try making a new template that's empty and remove all the scripts and load Jasny and Bootstrap only, then add the other scripts one by one until you find the problem.

**Comment by muhammad-ihsan** [comment] 2017-02-19 08:49
i did it before ask and try to find it out here sir @wordpresspluginpro , but no luck 💅

**Comment by Minstel** [comment] 2017-02-21 17:47
Duplicate of https://github.com/jasny/bootstrap/issues/253

**Closed by Minstel** 2017-02-21 17:47 UTC
Labels: duplicate
