### ISSUE TITLE
Offcanvas at right position bug animation on start

### ISSUE THREAD

**Issue by Rst0000** [jasny/bootstrap#465] opened 2016-07-13 07:40 UTC
Hello,

I'm using Jasny Bootstrap and I'm trying to place offcanvas menu at right of the screen. Unfortunately there is some kind of bug because when I trigger offcanvas (by data-attr), sidebar shows immediately without start animation. If it's positioned at left, everything is ok. I also tried to do it by dev tools at your example: http://www.jasny.net/bootstrap/examples/navmenu-push/ and I've changed "navmenu-fixed-left" to "navmenu-fixed-right" and result is the same. This is bug or I'm doing something wrong?

**Comment by gncreative** [comment] 2016-07-13 22:59
I am having the same issue and have been trying to find a solution.
My issue can be seen here:
http://mcneil.flywheelsites.com/

**Comment by Luizgpp** [comment] 2016-07-17 00:42
Same here!

**Comment by gazofnaz** [comment] 2016-08-05 16:14
@Rst0000 @gncreative @Luizgpp 

I posted a potential solution here: https://github.com/jasny/bootstrap/issues/253#issuecomment-237891098

**Comment by Minstel** [comment] 2017-02-21 17:47
Duplicate of https://github.com/jasny/bootstrap/issues/253

**Closed by Minstel** 2017-02-21 17:47 UTC
Labels: duplicate
