### ISSUE TITLE
Show offcanvas by default and resize canvas element when sliding

### ISSUE THREAD

**Issue by Cravid** [jasny/bootstrap#320] opened 2014-11-27 09:12 UTC
Hi,

I'd like to show the offcanvas navbar by default. When I just remove the offcanvas class from the navbar, it gets shown, but the data-canvas element of course is not adjusted. Can I somehow do this without statically add the left attribute to the canvas element?

Also can the data-canvas element automatically getting resized and adjusted to not move right out of the window? So that the canvas element has 100% width and when the navbar is opened it is adjusted to 100% - width of navbar and the content stays within the window?

**Comment by Minstel** [comment] 2017-02-22 03:56
@Cravid Second one is solved in PR https://github.com/jasny/bootstrap/pull/501 and will be published in comming release.
First one is a duplicate of https://github.com/jasny/bootstrap/issues/200
Closing this.

**Closed by Minstel** 2017-02-22 03:56 UTC
